version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    networks:
      - backend
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    depends_on:
      - nginx
    networks:
      - backend

  python-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-backend
    restart: always
    depends_on:
      - redis
    networks:
      - backend

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    depends_on:
      - nginx
      - redis
      - python-backend
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

volumes:
  mongo_data:
    driver: local

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
